"""empty message

Revision ID: 02f4d8630193
Revises: 9466995f8431
Create Date: 2024-03-26 23:11:22.412807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f4d8630193'
down_revision = '9466995f8431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
